###############################################
## .github/workflows/vulnerability-scan.yaml ##
###############################################
name: "Vulnerability Scan"

on: [push]

jobs:
  vulnerability_scan:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - run: docker build . -t testimage:${{ github.sha }}
        name: docker build
      - uses: Azure/container-scan@v0
        name: scan image for vulnerabilities
        id: container_scan
        # To fail the job when vulnerabilities are found, set to false
        continue-on-error: true
        with:
          image-name: testimage:${{ github.sha }}
          severity-threshold: MEDIUM
          run-quality-checks: true